<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="test-single" duration-ms="51357" started-at="2016-02-16T21:59:36Z" finished-at="2016-02-16T22:00:27Z">
    <groups>
    </groups>
    <test name="test-single" duration-ms="51357" started-at="2016-02-16T21:59:36Z" finished-at="2016-02-16T22:00:27Z">
      <class name="test.Cases.Xml.Parse.cpadTestPrograms">
        <test-method status="PASS" signature="logOpen()[pri:0, instance:test.Cases.Xml.Parse.cpadTestPrograms@3f0ee7cb]" name="logOpen" is-config="true" duration-ms="41" started-at="2016-02-16T16:59:36Z" finished-at="2016-02-16T16:59:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOpen -->
        <test-method status="PASS" signature="startTime()[pri:0, instance:test.Cases.Xml.Parse.cpadTestPrograms@3f0ee7cb]" name="startTime" is-config="true" duration-ms="21" started-at="2016-02-16T16:59:36Z" finished-at="2016-02-16T16:59:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="FAIL" signature="testCreatedOnOrderIsAscending()[pri:0, instance:test.Cases.Xml.Parse.cpadTestPrograms@3f0ee7cb]" name="testCreatedOnOrderIsAscending" duration-ms="51305" started-at="2016-02-16T16:59:36Z" finished-at="2016-02-16T17:00:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Error Cause: ---> TEST EXECUTION # 1 - Unexpected Results found!
   Location: ---> test.Cases.Xml.Parse\cpadTestPrograms\testCreatedOnOrderIsAscending, line # 178
   Expected: ---> true
     Actual: ---> false
   Detected: ---> 2016-02-16 17:00:27
    Runtime: ---> 0:00:51
   Subtotal: ---> 0:00:51
<class name="test.Cases.Xml.Parse.cpadTestPrograms"><methods><include name="testCreatedOnOrderIsAscending"/></methods></class>

Stack Traces: expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Error Cause: ---> TEST EXECUTION # 1 - Unexpected Results found!
   Location: ---> test.Cases.Xml.Parse\cpadTestPrograms\testCreatedOnOrderIsAscending, line # 178
   Expected: ---> true
     Actual: ---> false
   Detected: ---> 2016-02-16 17:00:27
    Runtime: ---> 0:00:51
   Subtotal: ---> 0:00:51
<class name="test.Cases.Xml.Parse.cpadTestPrograms"><methods><include name="testCreatedOnOrderIsAscending"/></methods></class>

Stack Traces: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at test.Cases.Xml.Parse.cpadTestPrograms.testCreatedOnOrderIsAscending(cpadTestPrograms.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatedOnOrderIsAscending -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:test.Cases.Xml.Parse.cpadTestPrograms@3f0ee7cb]" name="endTime" is-config="true" duration-ms="2" started-at="2016-02-16T17:00:27Z" finished-at="2016-02-16T17:00:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="logClose()[pri:0, instance:test.Cases.Xml.Parse.cpadTestPrograms@3f0ee7cb]" name="logClose" is-config="true" duration-ms="10" started-at="2016-02-16T17:00:27Z" finished-at="2016-02-16T17:00:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logClose -->
      </class> <!-- test.Cases.Xml.Parse.cpadTestPrograms -->
    </test> <!-- test-single -->
  </suite> <!-- test-single -->
</testng-results>
