<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="test-single" duration-ms="43978" started-at="2016-02-06T00:41:28Z" finished-at="2016-02-06T00:42:12Z">
    <groups>
    </groups>
    <test name="test-single" duration-ms="43978" started-at="2016-02-06T00:41:28Z" finished-at="2016-02-06T00:42:12Z">
      <class name="test.engine.cpadTestSingleURL">
        <test-method status="PASS" signature="logOpen()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="logOpen" is-config="true" duration-ms="92" started-at="2016-02-05T19:41:28Z" finished-at="2016-02-05T19:41:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOpen -->
        <test-method status="PASS" signature="startTime()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="startTime" is-config="true" duration-ms="10" started-at="2016-02-05T19:41:28Z" finished-at="2016-02-05T19:41:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTime -->
        <test-method status="FAIL" signature="testOrder()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="testOrder" duration-ms="43929" started-at="2016-02-05T19:41:28Z" finished-at="2016-02-05T19:42:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Error Cause: ---> Found Created On Records are Out of Order!
   Location: ---> test.engine\cpadTestSingleURL\testOrder, line # 177
   Expected: ---> true
     Actual: ---> false
   Detected: ---> 2016-02-05 19:42:10
    Runtime: ---> 0:00:42
   Subtotal: ---> 0:00:42
<class name="test.engine.cpadTestSingleURL"><methods><include name="testOrder"/></methods></class>

Stack Traces: expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Error Cause: ---> Found Created On Records are Out of Order!
   Location: ---> test.engine\cpadTestSingleURL\testOrder, line # 177
   Expected: ---> true
     Actual: ---> false
   Detected: ---> 2016-02-05 19:42:10
    Runtime: ---> 0:00:42
   Subtotal: ---> 0:00:42
<class name="test.engine.cpadTestSingleURL"><methods><include name="testOrder"/></methods></class>

Stack Traces: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at test.engine.cpadTestSingleURL.testOrder(cpadTestSingleURL.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOrder -->
        <test-method status="PASS" signature="endTime()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="endTime" is-config="true" duration-ms="10" started-at="2016-02-05T19:42:12Z" finished-at="2016-02-05T19:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTime -->
        <test-method status="PASS" signature="closeBrowsers()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="closeBrowsers" is-config="true" duration-ms="0" started-at="2016-02-05T19:42:12Z" finished-at="2016-02-05T19:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowsers -->
        <test-method status="PASS" signature="logClose()[pri:0, instance:test.engine.cpadTestSingleURL@16c0663d]" name="logClose" is-config="true" duration-ms="3" started-at="2016-02-05T19:42:12Z" finished-at="2016-02-05T19:42:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logClose -->
      </class> <!-- test.engine.cpadTestSingleURL -->
    </test> <!-- test-single -->
  </suite> <!-- test-single -->
</testng-results>
